import "./globals.css";
import Providers from "@/components/Providers";
import Sidebars from "@/components/Sidebar";
import SigninButton from "@/components/SigninButton";
export const metadata = {
  title: "Next-Auth Halhad",
  description: "Generated by halhad Dev",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="drawer">
            <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
            <div className="drawer-content flex flex-col">
              {/* Navbar */}
              <div className="w-full navbar bg-base-300">
                <div className="flex-none lg:hidden">
                  <label
                    htmlFor="my-drawer-3"
                    className="btn btn-square btn-ghost"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      className="inline-block w-6 h-6 stroke-current"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M4 6h16M4 12h16M4 18h16"
                      ></path>
                    </svg>
                  </label>
                </div>
                <div className="flex-1 px-2 mx-2">
                  <a href="/" className="flex items-center">
                    <img
                      src="/thinks.png"
                      className="h-8 mr-3"
                      alt="Flowbite Logo"
                    />
                  </a>
                </div>
                <div className="flex-none hidden lg:block">
                  <ul className="menu menu-horizontal">
                    {/* Navbar menu content here */}
                    <li>
                      <a href="/document">Documentation</a>
                    </li>
                    <li>
                      <a href="/swagger">Swagger Api</a>
                    </li>
                    <li>
                      <SigninButton />
                    </li>
                  </ul>
                </div>
              </div>
              {/* Page content here */} {children}
            </div>
            <div className="drawer-side">
              <label htmlFor="my-drawer-3" className="drawer-overlay"></label>

              <ul className="menu p-4 w-80 h-full bg-base-200">
                {/* Sidebar content here */}
                <li>
                  <a href="/document">Documentation</a>
                </li>
                <li>
                  <a href="/swagger">Swagger Api</a>
                </li>
                <li>
                  <SigninButton />
                </li>
              </ul>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
